# Generated by Django 5.1.4 on 2024-12-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
